Rakesh | BAH-1142 | BUG FIX: Ambiguous error message when CSV upload fails
Bahmni/bahmni-java-utils pull request #18
Opened 2021-02-09 12:00 UTC by rakesh-1010

## Description 
Some of the error messages that we get on CSV upload failure are technical in nature and cannot be understood by everyone or do not even point to a field that is causing the failure.

This is in case when there is a Fatal error while uploading.

Example:

java.lang.IndexOutOfBoundsException: toIndex = 31 this error is not meaningful to an end user. Instead a meaningful message stating that columns values are missing, in this case would be helpful

By resolving this every time the CSV fails upload, user will get a valid error message cause of failure and the columns/concepts that cause the issue.

## Fix

Instead of technical error, now a more generic error pointing to the row number will be displayed

2021-02-15 10:04 UTC, buvaneswari-arun requested changes

2021-02-15 10:04 UTC, buvaneswari-arun commented on bahmni-migrator/src/main/java/org/bahmni/csv/Migrator.java
> +                int failedRowNumber = allStages.getStages().get(0).getFailedRowNumber();
Can you make a null check here?  allStages.getStages() != null and size>=0

2021-02-16 07:03 UTC, rakesh-1010 commented on bahmni-migrator/src/main/java/org/bahmni/csv/Migrator.java
> +                int failedRowNumber = allStages.getStages().get(0).getFailedRowNumber();
Done @buvaneswari-arun

2021-02-16 07:04 UTC, buvaneswari-arun approved these changes

2021-02-16 07:04 UTC, merged