Bah 1195| Dependabot fixes -migrate to log4jv2
Bahmni/bahmni-java-utils pull request #33
Opened 2021-07-22 12:29 UTC by p-kamath

migrate to log4j v2 to mitigate the dependabot security alert.

2021-07-22 12:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Bahmni/bahmni-java-utils?pullRequest=33) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Bahmni/bahmni-java-utils?pullRequest=33) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Bahmni/bahmni-java-utils?pullRequest=33) it.</sub>

2021-12-11 11:25 UTC, N0-man commented on pom.xml
> +    <log4j.version>2.14.1</log4j.version>
There is a vulenrability identified in this specific version of log4j2 - [CVE-2021-44228](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-44228). Please bump the version to 2.15.0.

2021-12-11 11:28 UTC, N0-man requested changes
There is a critical vulnerability on log4j2 (2.14.1). Please update the version.

2022-01-13 09:31 UTC, gsluthra approved these changes

2022-01-21 05:10 UTC, N0-man approved these changes

2022-01-21 05:11 UTC, merged